# The name of the mod loader type to load (javafml) #mandatory
modLoader="javafml"
# A version range to match for said mod loader (34) #mandatory
loaderVersion="[35,)"
# A URL to refer people to when problems occur with this mod (GitHub Issues) #optional
issueTrackerURL="https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/issues"
# The name of the license that this mod is released under (Apache 2.0) #mandatory
license="Apache License, Version 2.0"

[[mods]]
    # A display name for the mod #mandatory
    displayName="Resynth - Growable Ores & Resources"
    # The modid of the mod #mandatory
    modId="resynth"
    # The version number of the mod - there's a few well known ${} variables useable here or just hardcode it #mandatory
    version="6.0.0"
    # The description text for the mod #mandatory
    description='''
    Adds tons of Plant Crops that grow Ores, Mob Drops, and Resources from both vanilla and many other popular mods!'''
    # A URL for the "homepage" for this mod #optional
    displayURL="https://resynth-minecraft-mod.github.io/"
    # A URL to query for updates for this mod. #optional
    updateJSONURL="https://resynth-minecraft-mod.github.io/versions.json"
    # A text field displayed in the mod UI #optional
    authors="Ki11er_wolf"
    # A text field displayed in the mod UI #optional
    credits="Ki11er_wolf, Aikini"
    # A file name (in the root of the mod JAR) containing a logo for display #optional
    logoFile="logo.png"

    [[dependencies.resynth]]

        modId="minecraft"

        mandatory=true

        versionRange="[1.16.4,1.17)"

        ordering="NONE"

        side="BOTH"
